name: "Customizable Docker Buildx"
description: "Configure docker to be used with buildx"
branding:
    icon: archive
    color: blue
inputs:
    tag:
        description: "Tags (comma separated) to apply to the image"
        default: "latest"
    imageName:
        description: "Name of the image"
        required: true
    dockerFile:
        description: "Name of the Dockerfile"
        default: "Dockerfile"
    buildArg:
        description: "Docker `--build-arg` flags (*comma separated*)"
        default: "none"
    publish:
        description: "Indicate if the builded image should be published on Docker HUB"
        default: "false"
    platform:
        description: "Platforms (comma separated) that should be used to build the image"
        default: "linux/amd64,linux/arm64,linux/arm/v7"
    dockerHubUser:
        description: "User that will publish the image, if indicated"
    dockerHubPassword:
        description: "Password of the dockerHubUser"
runs:
    using: 'node12'
    main: index.js
