name: "Customizable Docker Buildx"
description: "Configure docker to be used with buildx"
branding:
    icon: archive
    color: blue
inputs:
    tag:
        description: "Tags (comma separated) to apply to the image"
        default: "latest"
    imageName:
        description: "Name of the image"
        required: true
    dockerFile:
        description: "Name of the Dockerfile"
        default: "Dockerfile"
    buildArg:
        description: "Build arguments (comma separated) used to build the image"
        default: "none"
    publish:
        description: "Indicate if the builded image should be published on a registry"
        default: "false"
    platform:
        description: "Platforms (comma separated) that should be used to build the image"
        default: "linux/amd64,linux/arm64,linux/arm/v7"
    dockerUser:
        description: "User that will publish the image, if indicated"
    dockerHubUser:
        description: "(DEPRECATED) User that will publish the image, if indicated"
        deprecationMessage: 'Use dockerUser instead'
    dockerPassword:
        description: "Password of the dockerUser"
    dockerHubPassword:
        description: "(DEPRECATED) Password of the dockerUser"
        deprecationMessage: 'Use dockerPassword instead'
    dockerServer:
        description: "Server to login against"
        default: ""
    load:
        description: "Indicate if you want to load image into docker"
        default: "false"
    target:
        description: "Set the target build stage to build"
        default: ""
    context:
        description: "Set the context path"
        default: "."
runs:
    using: 'node12'
    main: index.js